### ISSUE TITLE
Bruke "snake case" i stedet for "kebab case" for attributter i tillitsrammeverket

### ISSUE THREAD

**Issue by runegri** [NorskHelsenett/Tillitsrammeverk#144]
I Issue https://github.com/NorskHelsenett/Tillitsrammeverk/issues/125 ble det foreslått å bruke "kebeb case" (bindestrek) for å skille mellom ord i attributt-navnene i tillitsrammeverket. Foreslår nå at vi endrer dette tilbake til "snake case" (understrek).

Årsaken til forslaget er at denne standarden allerede er innført i HelseID og brukes i produksjon i dag. Vi ser at det blir veldig forvirrende for konsumenter av HelseID å måtte forholde seg til ulike navnestandarder for de ulike informasjonselementene. HelseID kan ikke endre på navnestandarden, årsaken er at flere av disse er definert i protokollstandardene.

I dokumentasjonen til HelseID er det allerede brukt "snake case" der vi beskriver hvordan tillitsrammeverket skal brukes opp mot de ulike endepunktene, så denne endringen treffer kun beskrivelsen i Tillitsrammeverk-repoet.

**Comment by eirikbroen** [comment]
Pluss en på denne, fint å benytte samme navnestandard overalt

**Comment by steinarnoem** [comment]
+1 fra meg også - men må påpeke at jeg synes at snake-case er like fin som kebab-case. 

Her synes jeg at diktet "The Road Not Taken" av Robert Frost er veldig passende:

Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;

Then took the other, as just as fair,
And having perhaps the better claim,
Because it was grassy and wanted wear;
Though as for that the passing there
Had worn them really about the same,

And both that morning equally lay
In leaves no step had trodden black.
Oh, I kept the first for another day!
Yet knowing how way leads on to way,
I doubted if I should ever come back.

I shall be telling this with a sigh
Somewhere ages and ages hence:
Two roads diverged in a wood, and I—
I took the one less traveled by,
And that has made all the difference.

**Comment by micer2004** [comment]
Jeg vil helst skille på bruk av tillitsrammeverk i SAML-token hvor jeg vil ha "kebab case" (dvs. bruk av bindestrek slik at elementer henger sammen med XSPA-spesifikasjonen) og JWT/DPoP-token bruker gjerne "snake case" med understrek

**Comment by steinarnoem** [comment]
Legg inn tekst som sier at "casing" kan løses forskjellig i forskjellige formater, men at HelseID bruker samme standard som tillitsrammeverkspesifikasjon..

**Comment by steinarnoem** [comment]
Commit til branch https://github.com/NorskHelsenett/Tillitsrammeverk/tree/utproving-tillitsrammeverk-1.1
